name: tempo-numpyro
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.7.9
  - pandas=1.0.1
  - pip:
    # TODO: Change once changes are upstream
    # - mlops-tempo
    - /home/agm/Seldon/tempo
    - numpyro==0.6.0
    - mlserver==0.3.1.dev7
