---
- name: Install Certmanager
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ certmanager_yaml }}"

- name: Wait for cert-manager pods become ready
  shell: "kubectl wait --namespace=cert-manager --for=condition=Ready pods --selector app.kubernetes.io/instance=cert-manager --timeout=600s"
  register: cert_manager_pods_ready
      


