- op: add
  path: /spec/predictors/0/componentSpecs/0/spec/containers/0/resources
  value:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 1Gi
                    
