name: tempo
channels:
  - defaults
dependencies:
  - python=3.7.9
  - pip:
    - alibi-detect
    - dill
    - opencv-python-headless
    - mlops-tempo @ file:///home/clive/work/mlops/fork-tempo
    - mlserver==0.3.1.dev7
