# Adds namespace to all resources.
namespace: production
    
resources:
- tempo.yaml


patchesJson6902:
- target:
    group: serving.kubeflow.org
    version: v1beta1
    kind: InferenceService
    name: classifier
  path: patch_resources.yaml



