---
- name: Check if Istio {{ istio_version }} already downloaded.
  stat:
    path: "{{ inventory_dir }}/.resources/istio-{{ istio_version }}"
  register: istio_directory

- name: "Create .resources directory if does not exist: {{ inventory_dir }}/.resources/"
  ansible.builtin.file:
    path: "{{ inventory_dir }}/.resources/"
    state: directory
    mode: '0755'

- name: Download Istio {{ istio_version }}
  shell: "curl -L https://istio.io/downloadIstio | ISTIO_VERSION={{ istio_version }} sh -"
  args:
    chdir: "{{ inventory_dir }}/.resources"
    warn: false
  when: istio_directory.stat.exists == false

- name: Install Istio {{ istio_version }}
  shell: "./bin/istioctl install --set profile=default"
  args:
    chdir: "{{ inventory_dir }}/.resources/istio-{{ istio_version }}"

- name: Verify Install Istio {{ istio_version }}
  shell: "./bin/istioctl verify-install"
  args:
    chdir: "{{ inventory_dir }}/.resources/istio-{{ istio_version }}"
  when: istio_verify_install | bool

- name: Create Seldon Gateway
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      metadata:
        name: seldon-gateway
        namespace: istio-system
      spec:
        selector:
          app: istio-ingressgateway
          istio: ingressgateway
        servers:
        - hosts:
          - '*'
          port:
            name: http
            number: 80
            protocol: HTTP
