---
- name: "Check if KinD Cluster already exists: {{ kind_cluster_name }}"
  community.docker.docker_container_info:
    name: "{{ kind_cluster_name + '-control-plane' }}"
  register: cluster_check_result


- name: "Start KinD Cluster: '{{ kind_cluster_name }}'"
  command:
    argv:
      - kind
      - create
      - cluster
      - --name={{ kind_cluster_name }}
      - --image={{ kind_image_version }}
      - --config={{ kind_config_file }}
  register: kind_cluster_command
  when: not cluster_check_result.exists


- name: Echo message about KinD creation output
  ansible.builtin.debug:
    msg: "{{ kind_cluster_command.stderr.split('\n') }}"
  when: kind_cluster_command is not skipped


- name: "Export kubeconfig for KinD Cluster: '{{ kind_cluster_name }}'"
  command:
    argv:
      - kind
      - export
      - kubeconfig
      - --name={{ kind_cluster_name }}


- name: "Create a k8s namespace: {{ kind_kubectl_default_namespace }}"
  community.kubernetes.k8s:
    name: "{{ kind_kubectl_default_namespace }}"
    api_version: v1
    kind: Namespace
    state: present


- name: "Set default for kubectl namespace: {{ kind_kubectl_default_namespace }}"
  command:
    argv:
      - kubectl
      - config
      - set-context
      - --current
      - --namespace={{ kind_kubectl_default_namespace }}
