# Adds namespace to all resources.
namespace: production
    
resources:
- tempo.yaml


patchesJson6902:
- target:
    group: machinelearning.seldon.io
    version: v1
    kind: SeldonDeployment
    name: numpyro-divorce
  path: patch_resources.yaml



