---
- name: Install Seldon Core
  hosts: localhost
  roles:
    - istio
    - seldon_core
  vars:
    istio_version: 1.7.6
    seldon_core_version: master
    core_values:
      istio:
        enabled: true
        gateway: "seldon-gateway.istio-system.svc.cluster.local"
