---
- name: Install Seldon Core
  hosts: localhost
  roles:
    - istio
    - minio
    - seldon_core
  vars:
    istio_version: 1.7.6
    seldon_core_source_dir: "~/work/seldon-core"
    core_values:
      istio:
        enabled: true
        gateway: "seldon-gateway.istio-system.svc.cluster.local"
