---
- name: Create Workflow Role
  community.kubernetes.k8s:
    state: present
    name: workflow
    namespace: "{{ loop_namespace }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: workflow
      rules:
      - apiGroups:
        - ""
        resources:
        - pods
        verbs:
        - "*"
      - apiGroups:
        - "apps"
        resources:
        - deployments
        verbs:
        - "*"
      - apiGroups:
        - ""
        resources:
        - pods/log
        verbs:
        - "*"
      - apiGroups:
        - machinelearning.seldon.io
        resources:
        - "*"
        verbs:
        - "*"
  loop: "{{ workflow_namespaces }}"
  loop_control:
    loop_var: loop_namespace

- name: Create Workflow Role
  community.kubernetes.k8s:
    state: present
    name: workflow
    namespace: "{{ loop_namespace }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: workflow
  loop: "{{ workflow_namespaces }}"
  loop_control:
    loop_var: loop_namespace

- name: Create Rolebinding
  community.kubernetes.k8s:
    state: present
    name: workflow
    namespace: "{{ loop_namespace }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: workflow
      subjects:
      - kind: ServiceAccount
        name: workflow
        namespace: "{{ loop_namespace }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: workflow
  loop: "{{ workflow_namespaces }}"
  loop_control:
    loop_var: loop_namespace
