---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  annotations:
     serving.kubeflow.org/s3-endpoint: minio.minio-system.svc.cluster.local:9000 # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "0" # by default 1, for testing with minio you need to set to 0
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-tempo
secrets:
- name: minio-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kf-tempo
rules:
  - apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments/status
    verbs:
      - get
  - apiGroups:
      - serving.kubeflow.org
    resources:
      - inferenceservices/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tempo-pipeline-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kf-tempo
subjects:
  - kind: ServiceAccount
    name: kf-tempo
