---
- name: Create a k8s namespaces
  community.kubernetes.k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - "{{ seldon_system_namespace }}"
    - "{{ seldon_namespaces }}"
