---
- name: Create MinIO Secret
  community.kubernetes.k8s:
    state: present
    namespace: "{{ item }}"
    template: templates/minio_secret.j2
  with_items: "{{ seldon_namespaces }}"
  when: (minio_access_key is defined) and (minio_secret_key is defined) and (minio_namespace is defined)
