name: Tempo Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.7
          uses: actions/setup-python@v2
          with:
            python-version: 3.7.10
        - name: Install dependencies
          run: |
            make install-dev
        - name: Lint 
          run: |
            make lint
