name: Tempo Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: seldonio/python-builder:0.5

    steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: |
            make install-dev
        - name: Downloading test data
          run: |
            make tempo/tests/examples
        - name: Test
          run: |
            pytest tempo/tests/serve/test_pipeline.py::test_deploy_pipeline_docker -s
