name: Tempo Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.7
          uses: actions/setup-python@v2
          with:
            python-version: 3.7.10
        - name: Install dependencies
          run: |
            echo 'hello'
            # make install-dev
        - name: Downloading test data
          run: |
            echo 'hello 2'
            # make tempo/tests/examples
        - name: Test
          run: |
            id -u runner
            # pytest tempo/tests/serve/test_pipeline.py::test_deploy_pipeline_docker -s
